### ISSUE TITLE
prettytable dependency

### ISSUE THREAD

**Issue by ariebovenberg** [schollz/consensus-cookery#2]
Fun project! FYI you seem to have forgotten to include `prettytable` in the dependency list.

```
getting urls...
https://duckduckgo.com/?q=simple+cheesecake+recipe
https://duckduckgo.com/?q=favorite+cheesecake+recipe
https://duckduckgo.com/?q=delicious+cheesecake+recipe
https://duckduckgo.com/?q=diy+cheesecake+recipe
https://duckduckgo.com/?q=homemade+cheesecake+recipe
https://duckduckgo.com/?q=best+cheesecake+recipe
https://duckduckgo.com/?q=recipes+for+cheesecake+
https://duckduckgo.com/?q=easy+cheesecake+recipe
downloading 556 cheesecake recipes...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 556/556 [01:32<00:00,  1.63it/s]
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    start()
  File "/usr/local/var/pyenv/versions/sandbox3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/sandbox3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/var/pyenv/versions/sandbox3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/var/pyenv/versions/sandbox3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 83, in start
    from analyze import get_clusters
  File "/Users/ariebovenberg/Git/consensus-cookery/analyze.py", line 18, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'
```

Everything ran fine after installing it 😄 

edit: typo

**Comment by schollz** [comment]
Whoops, thanks!
